openapi: 3.0.3
info:
  title: API Auctions
  version: 1.0.0
  description: Auctios web
paths:
  /api/auctions/:
    get:
      operationId: auctions_list
      parameters:
      - name: page
        required: false
        in: query
        description: A page number within the paginated result set.
        schema:
          type: integer
      tags:
      - auctions
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedAuctionListCreateList'
          description: ''
    post:
      operationId: auctions_create
      tags:
      - auctions
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuctionListCreate'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/AuctionListCreate'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/AuctionListCreate'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuctionListCreate'
          description: ''
  /api/auctions/{auction_id}/bid/:
    get:
      operationId: auctions_bid_list
      parameters:
      - in: path
        name: auction_id
        schema:
          type: integer
        required: true
      - name: page
        required: false
        in: query
        description: A page number within the paginated result set.
        schema:
          type: integer
      tags:
      - auctions
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedBidListCreateList'
          description: ''
    post:
      operationId: auctions_bid_create
      parameters:
      - in: path
        name: auction_id
        schema:
          type: integer
        required: true
      tags:
      - auctions
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BidListCreate'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/BidListCreate'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/BidListCreate'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BidListCreate'
          description: ''
  /api/auctions/{auction_id}/bid/{id}/:
    get:
      operationId: auctions_bid_retrieve
      parameters:
      - in: path
        name: auction_id
        schema:
          type: integer
        required: true
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - auctions
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BidDetail'
          description: ''
    put:
      operationId: auctions_bid_update
      parameters:
      - in: path
        name: auction_id
        schema:
          type: integer
        required: true
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - auctions
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BidDetail'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/BidDetail'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/BidDetail'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BidDetail'
          description: ''
    patch:
      operationId: auctions_bid_partial_update
      parameters:
      - in: path
        name: auction_id
        schema:
          type: integer
        required: true
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - auctions
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedBidDetail'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedBidDetail'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedBidDetail'
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BidDetail'
          description: ''
    delete:
      operationId: auctions_bid_destroy
      parameters:
      - in: path
        name: auction_id
        schema:
          type: integer
        required: true
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - auctions
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '204':
          description: No response body
  /api/auctions/{id}/:
    get:
      operationId: auctions_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - auctions
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuctionDetail'
          description: ''
    put:
      operationId: auctions_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - auctions
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuctionDetail'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/AuctionDetail'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/AuctionDetail'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuctionDetail'
          description: ''
    patch:
      operationId: auctions_partial_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - auctions
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedAuctionDetail'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedAuctionDetail'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedAuctionDetail'
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuctionDetail'
          description: ''
    delete:
      operationId: auctions_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - auctions
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '204':
          description: No response body
  /api/auctions/categories/:
    get:
      operationId: auctions_categories_list
      parameters:
      - name: page
        required: false
        in: query
        description: A page number within the paginated result set.
        schema:
          type: integer
      tags:
      - auctions
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedCategoryListCreateList'
          description: ''
    post:
      operationId: auctions_categories_create
      tags:
      - auctions
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CategoryListCreate'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/CategoryListCreate'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/CategoryListCreate'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CategoryListCreate'
          description: ''
  /api/auctions/categories/{id}/:
    get:
      operationId: auctions_categories_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - auctions
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CategoryDetail'
          description: ''
    put:
      operationId: auctions_categories_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - auctions
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CategoryDetail'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/CategoryDetail'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/CategoryDetail'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CategoryDetail'
          description: ''
    patch:
      operationId: auctions_categories_partial_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - auctions
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedCategoryDetail'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedCategoryDetail'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedCategoryDetail'
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CategoryDetail'
          description: ''
    delete:
      operationId: auctions_categories_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - auctions
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '204':
          description: No response body
components:
  schemas:
    AuctionDetail:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        creation_date:
          type: string
          format: date-time
          readOnly: true
        closing_date:
          type: string
          format: date-time
        isOpen:
          type: boolean
          readOnly: true
        title:
          type: string
          maxLength: 150
        description:
          type: string
        price:
          type: string
          format: decimal
          pattern: ^-?\d{0,8}(?:\.\d{0,2})?$
        rating:
          type: string
          format: decimal
          pattern: ^-?\d{0,1}(?:\.\d{0,2})?$
        stock:
          type: integer
          maximum: 9223372036854775807
          minimum: -9223372036854775808
          format: int64
        brand:
          type: string
          maxLength: 100
        thumbnail:
          type: string
          format: uri
          maxLength: 200
        category:
          type: integer
      required:
      - brand
      - category
      - closing_date
      - creation_date
      - description
      - id
      - isOpen
      - price
      - rating
      - stock
      - thumbnail
      - title
    AuctionListCreate:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        creation_date:
          type: string
          format: date-time
          readOnly: true
        closing_date:
          type: string
          format: date-time
        isOpen:
          type: boolean
          readOnly: true
        title:
          type: string
          maxLength: 150
        description:
          type: string
        price:
          type: string
          format: decimal
          pattern: ^-?\d{0,8}(?:\.\d{0,2})?$
        rating:
          type: string
          format: decimal
          pattern: ^-?\d{0,1}(?:\.\d{0,2})?$
        stock:
          type: integer
          maximum: 9223372036854775807
          minimum: -9223372036854775808
          format: int64
        brand:
          type: string
          maxLength: 100
        thumbnail:
          type: string
          format: uri
          maxLength: 200
        category:
          type: integer
      required:
      - brand
      - category
      - closing_date
      - creation_date
      - description
      - id
      - isOpen
      - price
      - rating
      - stock
      - thumbnail
      - title
    BidDetail:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        auction:
          type: integer
        auction_title:
          type: string
          readOnly: true
        price:
          type: string
          format: decimal
          pattern: ^-?\d{0,8}(?:\.\d{0,2})?$
        creation_date:
          type: string
          format: date-time
          readOnly: true
        bidder:
          type: string
          maxLength: 100
      required:
      - auction
      - auction_title
      - bidder
      - creation_date
      - id
      - price
    BidListCreate:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        auction:
          type: integer
        price:
          type: string
          format: decimal
          pattern: ^-?\d{0,8}(?:\.\d{0,2})?$
        creation_date:
          type: string
          format: date-time
          readOnly: true
        bidder:
          type: string
          maxLength: 100
      required:
      - auction
      - bidder
      - creation_date
      - id
      - price
    CategoryDetail:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 50
      required:
      - id
      - name
    CategoryListCreate:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 50
      required:
      - id
      - name
    PaginatedAuctionListCreateList:
      type: object
      required:
      - count
      - results
      properties:
        count:
          type: integer
          example: 123
        next:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?page=4
        previous:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?page=2
        results:
          type: array
          items:
            $ref: '#/components/schemas/AuctionListCreate'
    PaginatedBidListCreateList:
      type: object
      required:
      - count
      - results
      properties:
        count:
          type: integer
          example: 123
        next:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?page=4
        previous:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?page=2
        results:
          type: array
          items:
            $ref: '#/components/schemas/BidListCreate'
    PaginatedCategoryListCreateList:
      type: object
      required:
      - count
      - results
      properties:
        count:
          type: integer
          example: 123
        next:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?page=4
        previous:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?page=2
        results:
          type: array
          items:
            $ref: '#/components/schemas/CategoryListCreate'
    PatchedAuctionDetail:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        creation_date:
          type: string
          format: date-time
          readOnly: true
        closing_date:
          type: string
          format: date-time
        isOpen:
          type: boolean
          readOnly: true
        title:
          type: string
          maxLength: 150
        description:
          type: string
        price:
          type: string
          format: decimal
          pattern: ^-?\d{0,8}(?:\.\d{0,2})?$
        rating:
          type: string
          format: decimal
          pattern: ^-?\d{0,1}(?:\.\d{0,2})?$
        stock:
          type: integer
          maximum: 9223372036854775807
          minimum: -9223372036854775808
          format: int64
        brand:
          type: string
          maxLength: 100
        thumbnail:
          type: string
          format: uri
          maxLength: 200
        category:
          type: integer
    PatchedBidDetail:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        auction:
          type: integer
        auction_title:
          type: string
          readOnly: true
        price:
          type: string
          format: decimal
          pattern: ^-?\d{0,8}(?:\.\d{0,2})?$
        creation_date:
          type: string
          format: date-time
          readOnly: true
        bidder:
          type: string
          maxLength: 100
    PatchedCategoryDetail:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 50
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
