# Generated by Django 5.1.7 on 2025-05-15 11:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bid',
            unique_together={('bidder', 'auction')},
        ),
    ]
