# Generated by Django 5.1.7 on 2025-05-11 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_rating_value'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rating',
            options={'ordering': ('id',)},
        ),
    ]
