# Generated by Django 5.1.7 on 2025-04-13 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auction_auctioneer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bid',
            options={'ordering': ('price',)},
        ),
    ]
